{{- if .Values.logstash.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: {{ .Values.global.namespace }}
data:
  logstash.conf: |
{{ .Values.logstash.config.logstashConf | indent 4 }}
  logstash.yml: |
{{ .Values.logstash.config.logstashYml | indent 4 }}
{{- end }}
