{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Values.global.namespace }}
data:
  filebeat.yml: |
{{ .Values.filebeat.config.filebeatYml | indent 4 }}
{{- end }}
