{{- if .Values.filebeat.enabled }}
{{- if .Values.filebeat.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.filebeat.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
{{- end }}
