{{- if .Values.kibana.enabled }}
{{- if .Values.kibana.serviceAccountToken }}
apiVersion: v1
kind: Secret
metadata:
  name: kibana-token
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  token: {{ .Values.kibana.serviceAccountToken | quote }}
{{- end }}
{{- end }}
