{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.global.namespace }}
  labels:
    app: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: kibana
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
{{- end }}
