{{- if .Values.elasticsearch.enabled }}
{{- if .Values.elasticsearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.elasticsearch.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClassName }}
{{- end }}
{{- end }}
