{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.elasticsearch.security.username | quote }}
  password: {{ .Values.elasticsearch.security.password | quote }}
{{- end }}
